version: '3'

services:
    php5.6:
        image: chensk/php5.6:latest
        depends_on:
            - mysql-db
            - redis-db
        links:
            - mysql-db:mysql-db
            - redis-db:redis-db
        volumes:
            - /Users/chensk/work/www:/www
	    - ./php.ini:/usr/local/etc/php/
            - ./logs/php-fpm:/var/log/php-fpm:rw
        ports:
              - "9000:9000"
        restart: always
        networks:
            - code-network

    nginx:
        image: nginx:1.11
        depends_on:
            - php5.6
        links:
            - php5.6:php5.6
        ports:
            - "8080:80"
        volumes:
            - /Users/chensk/work/www:/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
        ports:
              - "80:80"
              - "8080:8080"
              - "443:443"
        restart: always
        networks:
            - code-network
    mysql-db:
        image: mysql:5.7
        ports:
            - "4306:3306"
        volumes:
            - /Users/chensk/work/www/mysql:/www
            - ./logs/mysql:/var/lib/mysql-logs:rw
            #- /Users/chensk/work/mysql/conf.d:/etc/mysql/conf.d:ro
        environment:
            MYSQL_ROOT_PASSWORD : windows8
            MYSQL_DATABASE : chensk
            MYSQL_USER : root
            MYSQL_PASSWORD : windows8
        restart: always
        command: "--character-set-server=utf8"
        networks:
            - code-network
    redis-db:
        image: redis:3.2
        ports:
            - "6379:6379"
        volumes:
            - /Users/chensk/work/www/redis:/www
        restart: always
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
