version: '3'

services:
    php5.6:
        image: chenshaokun/php5:latest
        depends_on:
            - mysql-db
            - redis-db
        links:
            - mysql-db:mysql-db
            - redis-db:redis-db
        volumes:
            - /home/server/work/www:/www
            - ./logs/php-fpm:/var/log/php-fpm:rw
        ports:
              - "9000:9000"
        restart: always
        networks:
            - code-network
    nginx:
        image: nginx:latest
        depends_on:
            - php5.6
        links:
            - php5.6:php5.6
        ports:
            - "8080:80"
        volumes:
            - /home/server/work/www:/www
            - ./racoon-nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
        ports:
              - "80:80"
              - "8080:8080"
              - "443:443"
        restart: always
        networks:
            - code-network
    mysql-db:
        image: mysql:5.7
        ports:
            - "4306:3306"
        volumes:
            - /home/server/work/mysql:/var/lib/mysql
            - ./logs/mysql:/var/lib/mysql-logs:rw
        environment:
            MYSQL_ROOT_PASSWORD : root
            MYSQL_DATABASE : mydatabase
            MYSQL_USER : root
            MYSQL_PASSWORD : root
        restart: always
        command: "--character-set-server=utf8"
        networks:
            - code-network
    redis-db:
        image: redis:latest
        ports:
            - "6380:6379"
        volumes:
            - /home/server/work/redis:/www
        restart: always
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
